name: Test

on: [
  push,
  pull_request
]

env:
  DB_DATABASE: wotp
  DB_USER: root
  DB_PASSWORD: root

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: yarn
    - name: Lint
      run: yarn lint
    - name: Prepare
      run: |
        sudo /etc/init.d/mysql start
        mysql -e 'CREATE DATABASE ${{ env.DB_DATABASE }};' -u${{ env.DB_USER }} -p${{ env.DB_PASSWORD }}

        cp -f src/config.ci.js src/config.js
    - name: Test
      run: yarn test
